apiVersion: apps/v1
kind: Deployment
metadata:
  name: commafeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: commafeed
  template:
    metadata:
      labels:
        app: commafeed
    spec:
      containers:
        - name: commafeed
          image: athou/commafeed:latest-h2
          ports:
            - containerPort: 8082
          volumeMounts:
            - name: commafeed-data
              mountPath: /commafeed/data
      volumes:
        - name: commafeed-data
          persistentVolumeClaim:
            claimName: commafeed-pvc
