{
  config,
  ...
}:
{
  accounts.email = {
    maildirBasePath = "${config.xdg.dataHome}/Mail";

    accounts =
      let
        realName = "Volodia P.-G.";

        mbsync.enable = true;
        msmtp.enable = true;
        notmuch = {
          enable = true;
          neomutt.enable = true;
        };

        neomutt = {
          enable = true;
          mailboxType = "imap";
          extraMailboxes = [
            "Drafts"
            "Sent"
            "Trash"
            "Junk"
            "Archive"
          ];
        };
      in
      {
        inria = {
          primary = true;
          inherit
            realName
            mbsync
            msmtp
            notmuch
            neomutt
            ;
          address = "vparolgu@inria.fr";
          userName = "vparolgu";
          passwordCommand = "cat ${config.age.secrets.mail_inria_password.path}";
          imap = {
            host = "imap.inria.fr";
          };
          smtp = {
            host = "smtp.inria.fr";
          };
        };
      };
  };

  programs = {
    mbsync.enable = true;
    msmtp.enable = true;
    notmuch.enable = true;

    neomutt = {
      enable = true;
      vimKeys = true;

      sidebar = {
        enable = true;
        shortPath = true;
        width = 25;
      };

      # from https://github.com/LukeSmithxyz/mutt-wizard

      extraConfig = ''
        bind index gT noop
        bind index dT noop
        bind index dt noop
        bind index gg noop
        bind index gt noop
        bind index dd noop
        bind pager gT noop
        bind pager gg noop

        set header_cache = ~/.cache/neomutt
        set message_cachedir = $header_cache

        # This file contains all of mutt-wizard's default settings.
        # mutt-wizard will have this file sourced from your muttrc.
        # In the interest of seamless updating, do not edit this file.
        # If you want to override any settings, set those in your muttrc.
        set send_charset="us-ascii:utf-8"
        # set mailcap_path = $HOME/.config/mutt/mailcap:/usr/local/share/mutt-wizard/mailcap:$mailcap_path
        set mime_type_query_command = "file --mime-type -b %s"
        set date_format="%y/%m/%d %I:%M%p"
        set index_format="%2C %Z %?X?A& ? %D %-15.15F %s (%-4.4c)"
        set sort = 'reverse-date'
        set smtp_authenticators = 'gssapi:login'
        set query_command = "abook --mutt-query '%s'"
        set rfc2047_parameters = yes
        set sleep_time = 0		# Pause 0 seconds for informational messages
        set markers = no		# Disables the `+` displayed at line wraps
        set mark_old = no		# Unread mail stay unread until read
        set mime_forward = no	# mail body is forwarded as text
        set forward_attachments = yes	# attachments are forwarded with mail
        set wait_key = no		# mutt won't ask "press key to continue"
        set fast_reply			# skip to compose when replying
        set fcc_attach			# save attachments with the body
        set forward_format = "Fwd: %s"	# format of subject when forwarding
        set forward_quote		# include message in forwards
        set reverse_name		# reply as whomever it was to
        set include			# include message in replies
        set mail_check=60 # to avoid lags using IMAP with some email providers (yahoo for example)
        auto_view text/html		# automatically show html (mailcap uses lynx)
        auto_view application/pgp-encrypted
        #set display_filter = "tac | sed '/\\\[-- Autoview/,+1d' | tac" # Suppress autoview messages.
        alternative_order text/plain text/enriched text/html

        bind index,pager i noop
        bind index,pager g noop
        bind index \Cf noop
        bind index,pager M noop
        bind index,pager C noop

        # General rebindings
        bind index gg first-entry
        bind index j next-entry
        bind index k previous-entry
        bind attach <return> view-mailcap
        bind attach l view-mailcap
        bind editor <space> noop
        bind index G last-entry
        bind pager,attach h exit
        bind pager j next-line
        bind pager k previous-line
        bind pager l view-attachments
        bind index D delete-message
        bind index U undelete-message
        bind index L limit
        bind index h noop
        bind index l display-message
        bind index,query <space> tag-entry
        #bind browser h goto-parent
        macro browser h '<change-dir><kill-line>..<enter>' "Go to parent folder"
        bind index,pager H view-raw-message
        bind browser l select-entry
        bind browser gg top-page
        bind browser G bottom-page
        bind pager gg top
        bind pager G bottom
        bind index,pager,browser d half-down
        bind index,pager,browser u half-up
        bind index,pager S sync-mailbox
        bind index,pager R group-reply
        bind index \031 previous-undeleted	# Mouse wheel
        bind index \005 next-undeleted		# Mouse wheel
        bind pager \031 previous-line		# Mouse wheel
        bind pager \005 next-line		# Mouse wheel
        bind editor <Tab> complete-query

        macro index,pager gi "<change-folder>=INBOX<enter>" "go to inbox"
        macro index,pager Mi ";<save-message>=INBOX<enter>" "move mail to inbox"
        macro index,pager Ci ";<copy-message>=INBOX<enter>" "copy mail to inbox"
        macro index,pager gd "<change-folder>=Drafts<enter>" "go to drafts"
        macro index,pager Md ";<save-message>=Drafts<enter>" "move mail to drafts"
        macro index,pager Cd ";<copy-message>=Drafts<enter>" "copy mail to drafts"
        macro index,pager gj "<change-folder>=Junk<enter>" "go to junk"
        macro index,pager Mj ";<save-message>=Junk<enter>" "move mail to junk"
        macro index,pager Cj ";<copy-message>=Junk<enter>" "copy mail to junk"
        macro index,pager gt "<change-folder>=Trash<enter>" "go to trash"
        macro index,pager Mt ";<save-message>=Trash<enter>" "move mail to trash"
        macro index,pager Ct ";<copy-message>=Trash<enter>" "copy mail to trash"
        macro index,pager gs "<change-folder>=Sent<enter>" "go to sent"
        macro index,pager Ms ";<save-message>=Sent<enter>" "move mail to sent"
        macro index,pager Cs ";<copy-message>=Sent<enter>" "copy mail to sent"
        macro index,pager ga "<change-folder>=Archive<enter>" "go to archive"
        macro index,pager Ma ";<save-message>=Archive<enter>" "move mail to archive"
        macro index,pager Ca ";<copy-message>=Archive<enter>" "copy mail to archive"

        #set crypt_auto_sign = yes
        #set crypt_opportunistic_encrypt = yes
        #set pgp_self_encrypt = yes
        #set pgp_default_key  = 'your@gpgemailaddre.ss'
        macro index \eg "<enter-command>unset wait_key<enter><shell-escape>gpg --list-secret-keys; printf 'Enter email ID of user to publish: '; read eID; printf 'Enter fingerprint of GPG key to publish: '; read eFGPT; $prefix/libexec/gpg-wks-client --create \\\$eFGPT \\\$eID | msmtp --read-envelope-from --read-recipients -a $fulladdr<enter>"  "publish GPG key to WKS provider"
        macro index \eh "<pipe-message>$prefix/libexec/gpg-wks-client --receive | msmtp --read-envelope-from --read-recipients -a $fulladdr<enter>" "confirm GPG publication"

        macro index,pager a "<enter-command>set my_pipe_decode=\$pipe_decode pipe_decode<return><pipe-message>abook --add-email<return><enter-command>set pipe_decode=\$my_pipe_decode; unset my_pipe_decode<return>" "add the sender address to abook"
        macro index \Cr "T~U<enter><tag-prefix><clear-flag>N<untag-pattern>.<enter>" "mark all messages as read"
        macro index O "<shell-escape>mailsync<enter>" "run mailsync to sync all mail"
        macro index \Cf "<enter-command>unset wait_key<enter><shell-escape>printf 'Enter a search term to find with notmuch: '; read x; echo \$x >\"\$\{XDG_CACHE_HOME:-\$HOME/.cache}/mutt_terms\"<enter><limit>~i \"\`notmuch search --output=messages \$(cat \"\$\{XDG_CACHE_HOME:-\$HOME/.cache}/mutt_terms\") | head -n 600 | perl -le '@a=<>;s/\^id:// for@a;$,=\"|\";print@a' | perl -le '@a=<>; chomp@a; s/\\+/\\\\+/g for@a; s/\\$/\\\\\\$/g for@a;print@a' \`\"<enter>" "show only messages matching a notmuch pattern"
        macro index A "<limit>all\n" "show all messages (undo limit)"

        # Sidebar mappings
        set sidebar_visible = yes
        set sidebar_width = 20
        set sidebar_short_path = yes
        set sidebar_next_new_wrap = yes
        set mail_check_stats
        set sidebar_format = '%D%?F? [%F]?%* %?N?%N/? %?S?%S?'
        bind index,pager \Ck sidebar-prev
        bind index,pager \Cj sidebar-next
        bind index,pager \Co sidebar-open
        bind index,pager \Cp sidebar-prev-new
        bind index,pager \Cn sidebar-next-new
        bind index,pager B sidebar-toggle-visible

        color normal		  default default         # Text is "Text"
        color index		    color2 default ~N       # New Messages are Green
        color index		    color1 default ~F       # Flagged messages are Red
        color index		    color13 default ~T      # Tagged Messages are Red
        color index		    color1 default ~D       # Messages to delete are Red
        color attachment	color5 default          # Attachments are Pink
        color signature	  color8 default          # Signatures are Surface 2
        color search		  color4 default          # Highlighted results are Blue

        color indicator		default color8          # currently highlighted message Surface 2=Background Text=Foreground
        color error		    color1 default          # error messages are Red
        color status		  color15 default         # status line "Subtext 0"
        color tree        color15 default         # thread tree arrows Subtext 0
        color tilde       color15 default         # blank line padding Subtext 0

        color hdrdefault  color13 default         # default headers Pink
        color header		  color13 default "^From:"
        color header	 	  color13 default "^Subject:"

        color quoted		  color15 default         # Subtext 0
        color quoted1		  color7 default          # Subtext 1
        color quoted2		  color8 default          # Surface 2
        color quoted3		  color0 default          # Surface 1
        color quoted4		  color0 default
        color quoted5		  color0 default

        color body		color2 default		[\-\.+_a-zA-Z0-9]+@[\-\.a-zA-Z0-9]+               # email addresses Green
        color body	  color2 default		(https?|ftp)://[\-\.,/%~_:?&=\#a-zA-Z0-9]+        # URLs Green
        color body		color4 default		(^|[[:space:]])\\*[^[:space:]]+\\*([[:space:]]|$) # *bold* text Blue
        color body		color4 default		(^|[[:space:]])_[^[:space:]]+_([[:space:]]|$)     # _underlined_ text Blue
        color body		color4 default		(^|[[:space:]])/[^[:space:]]+/([[:space:]]|$)     # /italic/ text Blue

        color sidebar_flagged   color1 default    # Mailboxes with flagged mails are Red
        color sidebar_new       color10 default   # Mailboxes with new mail are Green
      '';
    };
  };
}
