r vf toggle vapoursynth=~~/rife.py:2:24 ; show-text "RIFE interpolation 46"
t vf toggle vapoursynth=~~/rife_high.py:2:24 ; show-text "RIFE interpolation (high 46)"
g vf toggle vapoursynth=~~/rife25.py:2:24 ; show-text "RIFE interpolation (25)"
