profile=gpu-hq

vo=gpu-next
hwdec=auto-copy
hr-seek-framedrop=no

hdr-compute-peak=no

# wayland-disable-vsync=yes
video-sync=display-resample

# Enable VRR for Linux DRM/KMS outputs (if applicable)
drm-vrr-enabled=yes

interpolation=no

# gpu-api=vulkan
# vulkan-async-compute=yes
# vulkan-async-transfer=yes
# vulkan-queue-count=1
# autofit=85%x85%
# dither=error-diffusion
# deband=yes
# deband-iterations=2
# deband-threshold=20
# deband-range=16
# scale=ewa_hanning
# scale-radius=3.2383154841662362
# dscale=mitchell
# scale-antiring=0
# cscale-antiring=0
# correct-downscaling=yes
# linear-downscaling=no
# sigmoid-upscling=yes
# video-sync=display-resample
# tscale=box
# tscale-window=quadric
# tscale-radius=1.1
# tscale-clamp=0.0
# interpolation=no
# blend-subtitles=no
# hdr-compute-peak=yes
# tone-mapping=mobius

# osd-msg1="FPS: ${estimated-display-fps}"

# target-trc=srgb

# hwdec=auto-safe
# scale=ewa_lanczossharp
# cscale=ewa_lanczossharp
# video-sync=display-resample
# interpolation
# tscale=oversample
ytdl-format=bestvideo[height<=?1080]+bestaudio/best
# ytdl-format=bestvideo[height<=?1080][fps<=?60][vcodec!=?vp9]+bestaudio/best
# ytdl-format=bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4
#vo=gpup
#ytdl-format=bestvideo[height<=?1080]+bestaudio/best
#gpu-context=wayland
# ytdl=yes

# ytdl-format=399[fps<=30]+251/248+251/137+251/398+251/302+251/298+251/247+251/136+251/397+251/244+251/135+251/396+251/243+251/134+251/bestvideo+bestaudio/best
# ytdl-format="best[vcodec!=vp9]"
# ytdl-format="bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"
cache=yes
cache-pause=yes
cache-pause-wait=1
cache-secs=120
