# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_volodia age14eun5ps0y50qlspkz63j7uwrxt2mehhzut6rwsj2nckgdrc2rgtqfx6jg2
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *admin_volodia