# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  scx = {
    pname = "scx";
    version = "7c09a8833235f708d7f0e64e794001aebe5182d2";
    src = fetchFromGitHub {
      owner = "sched-ext";
      repo = "scx";
      rev = "7c09a8833235f708d7f0e64e794001aebe5182d2";
      fetchSubmodules = false;
      sha256 = "sha256-Fj83IB0tKYal/EEa/S6+VKjcRW6nn3pqd5zDyubxw2I=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-Fj83IB0tKYal_EEa_S6+VKjcRW6nn3pqd5zDyubxw2I=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-04-02";
  };
}
