# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  scx = {
    pname = "scx";
    version = "aee2474ae36dbab2c79061653b05b0c6b6fd5520";
    src = fetchFromGitHub {
      owner = "sched-ext";
      repo = "scx";
      rev = "aee2474ae36dbab2c79061653b05b0c6b6fd5520";
      fetchSubmodules = false;
      sha256 = "sha256-rVWUR3+6gv6bHqxovdg7pM+2QsbFyVmjWB8MpOYFENg=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-rVWUR3+6gv6bHqxovdg7pM+2QsbFyVmjWB8MpOYFENg=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-03-25";
  };
}
