# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  scx = {
    pname = "scx";
    version = "8e1cc4bdc74e39140de697c4f24bf50a88c30f5b";
    src = fetchFromGitHub {
      owner = "sched-ext";
      repo = "scx";
      rev = "8e1cc4bdc74e39140de697c4f24bf50a88c30f5b";
      fetchSubmodules = false;
      sha256 = "sha256-ReliULm0ULNo8pfaPBu+Kc4i9euglBsJzBRLeRyDoD0=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./. + "/sha256-ReliULm0ULNo8pfaPBu+Kc4i9euglBsJzBRLeRyDoD0=/Cargo.lock";
      outputHashes = {
        
      };
    };
    date = "2026-04-15";
  };
}
