[accessibility]
ui_scale = 1.0

[bar.main]
background_opacity = 0.69999998435378075
capsule_thickness = 0.99999998137354851
center = [ "workspaces" ]
end = [ "media", "tray", "battery", "volume", "brightness", "clock" ]
font_weight = 400
margin_edge = 1
margin_ends = 300
margin_h = 4
margin_v = 4
padding = 25
position = "bottom"
radius = 12
scale = 1.1000000089406967
shadow = false
start = [ "control-center", "notifications", "cpu" ]
thickness = 25
widget_spacing = 12

[brightness]
enable_ddcutil = true

[dock]
background_opacity = 0.79999998211860657
item_spacing = 12

[idle.behavior.lock]
action = "lock"
enabled = true
timeout = 200

[idle.behavior.screen-off]
action = "screen_off"
enabled = true
timeout = 120

[location]
address = "Rennes"

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@DP-3",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000003",
    "lockscreen-widget-0000000000000004"
]

    [lockscreen_widgets.grid]
    cell_size = 64
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@DP-3"]
    box_height = 64.0
    box_width = 400.0
    cx = 1433.5
    cy = 600.0
    output = "DP-3"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@DP-3".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = true
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 192.0
    box_width = 576.0
    cx = 1433.5
    cy = 376.0
    output = "DP-3"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background = false
        center_text = true
        clock_style = "digital"
        format = "{:%H:%M}"
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1433.5
    cy = 796.0
    output = "DP-3"
    rotation = 0.0
    type = "media_player"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000002.settings]
        background = false
        hide_when_no_media = true
        shadow = false

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000003]
    box_height = 128.0
    box_width = 208.0
    cx = 1433.5
    cy = 1048.0
    output = "DP-3"
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000003.settings]
        background = false
        display = "graph"
        shadow = false
        show_label = true
        stat = "cpu_usage"
        stat2 = "cpu_temp"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000004]
    box_height = 64.0
    box_width = 384.0
    cx = 1433.5
    cy = 472.0
    output = "DP-3"
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000004.settings]
        background = false
        center_text = true
        clock_style = "digital"
        format = "{:%A %d %B } "
        shadow = false

[nightlight]
temperature_day = 6500
temperature_night = 4000

[notification]
background_opacity = 0.59999998658895493
position = "bottom_center"

[osd]
background_opacity = 0.59999998658895493
orientation = "vertical"
position = "bottom_right"
position_vertical = "center_right"

    [osd.kinds]
    media = false

[plugin_settings."nzlov/daily-wallpaper"]
locale = "fr-FR"

[plugins]
enabled = [ "nzlov/daily-wallpaper" ]

[shell]
avatar_path = "/home/volodia/Pictures/.face"
launch_apps_as_systemd_services = true
polkit_agent = true
screen_time_enabled = true
telemetry_enabled = false

    [shell.animation]
    enabled = true

    [shell.panel]
    open_near_click_control_center = true
    transparency_mode = "glass"

    [shell.shadow]
    direction = "center"

[theme]
builtin = "Catppuccin"
mode = "dark"
source = "builtin"

[wallpaper]
directory = "/home/volodia/Pictures/Wallpapers"
enabled = true
fill_color = "#000000"
fill_mode = "crop"
transition = [ "fade", "disc", "stripes", "wipe", "honeycomb" ]
transition_duration = 1500
transition_on_startup = true

    [wallpaper.default]
    path = "/home/volodia/Pictures/Wallpapers/daily-wallpaper/bing-fr-fr-2026-07-20.jpg"

    [wallpaper.last]
    path = "/home/volodia/Pictures/Wallpapers/daily-wallpaper/bing-fr-fr-2026-07-20.jpg"

    [wallpaper.monitors.DP-3]
    path = "/home/volodia/Pictures/Wallpapers/daily-wallpaper/bing-fr-fr-2026-07-20.jpg"

[weather]
effects = true
enabled = true

[widget.clock]
format = "{:%H:%M %A %d %B } "
tooltip_format = "{:%H:%M %a, %b %d}"

[widget.control-center]
glyph = "snowflake"

[widget.cpu]
stat = "cpu_temp"

[widget.media]
art_size = 20

[widget.workspaces]
anchor = true
labels_only_when_occupied = true
