# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  lib,
  modulesPath,
  ...
}:
{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  nixpkgs.hostPlatform = "aarch64-linux";

  hardware.enableRedistributableFirmware = true;
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    settings = {
      General = {
        # Keep adapter in page-scan mode for instant reconnects
        FastConnectable = true;
        # ZMK uses "Just Works" pairing – always allow re-pairing
        JustWorksRepairing = "always";
        # Better LE handling & battery reporting
        Experimental = true;
      };
      LE = {
        # Tighter polling interval (7.5–11.25 ms) for lower input latency
        MinConnectionInterval = 6;
        MaxConnectionInterval = 9;
        ConnectionLatency = 0;
      };
      Policy = {
        AutoEnable = true;
        ReconnectAttempts = 7;
        ReconnectIntervals = "1,2,4,8,16,32,64";
      };
    };
  };
  boot = {
    initrd = {
      availableKernelModules = [
        "nvme"
        "usb_storage"
        "sdhci_pci"
      ];
      kernelModules = [ ];
    };
    extraModulePackages = [ ];
    kernelParams = [
      "usbcore.autosuspend=-1"
    ];
    #loader.grub.device = "nodev";
  };

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-label/BOOT";
      fsType = "vfat";
    };
  };

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp0s31f6.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp0s20f3.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = lib.mkForce "shedutil";
}
