apiVersion: apps/v1
kind: Deployment
metadata:
  name: fizzy
  namespace: fizzy
spec:
  replicas: 1
  # Downtime acceptable; RWO volume can't be mounted by two pods at once
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: fizzy
  template:
    metadata:
      labels:
        app: fizzy
    spec:
      containers:
        - name: fizzy
          image: ghcr.io/basecamp/fizzy:latest@sha256:a58edf0c0971430c5f36126643393fe576f6730e7c6631e59a58b1fd47917c75
          ports:
            - containerPort: 80
          volumeMounts:
            - name: fizzy-data
              mountPath: /rails/storage
          resources:
            requests:
              memory: 600Mi
              cpu: 400m
            limits:
              memory: 900Mi
              cpu: 1000m
          env:
            - name: BASE_URL
              value: https://fizzy.goblin-alewife.ts.net
            - name: MAILER_FROM_ADDRESS
              value: bot.volodia@gmail.com
            - name: DISABLE_SSL
              value: "true"
            - name: SMTP_ADDRESS
              value: smtp.gmail.com
            - name: SMTP_USERNAME
              value: bot.volodia@gmail.com
            # Fewer glibc malloc arenas: less memory fragmentation
            - name: MALLOC_ARENA_MAX
              value: "1"
            # 1 forked workers: low memory and decouples processes
            - name: WEB_CONCURRENCY
              value: "1"
            # Threads are enough for 1-5 users and cheap
            - name: RAILS_MAX_THREADS
              value: "5"
            # Run Solid Queue supervisor inside Puma: no separate jobs process
            - name: SOLID_QUEUE_IN_PUMA
              value: "true"
            # Single job-processing thread/process
            - name: JOB_CONCURRENCY
              value: "1"
            # Enables faster Ruby with JIT
            - name: RUBY_YJIT_ENABLE
              value: "1"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: fizzy-env
                  key: secret_key_base
            - name: SMTP_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: fizzy-env
                  key: smtp_password

      volumes:
        - name: fizzy-data
          persistentVolumeClaim:
            claimName: fizzy-pvc
