apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fizzy-ingress
  namespace: fizzy
  annotations:
    tailscale.com/proxy-group: ingress-proxies
    tailscale.com/tags: tag:k8s
spec:
  ingressClassName: tailscale
  tls:
    - hosts:
        - fizzy
  defaultBackend:
    service:
      name: fizzy-service
      port:
        number: 80
