vault-edit:
    #!/usr/bin/env bash
    cd {{ justfile_dir() }}
    ansible-vault edit --vault-password-file ~/.config/ansible/vault-pass inventory/group_vars/all/vault.yml

vault-encrypt:
    #!/usr/bin/env bash
    cd {{ justfile_dir() }}
    ansible-vault encrypt --vault-password-file ~/.config/ansible/vault-pass inventory/group_vars/all/vault.yml

macos:
    ansible-playbook -K playbooks/macos.yml

msi host="msi" *flags="":
    ansible-playbook playbooks/site.yml --limit msi -e ansible_host={{ host }} -K {{ flags }}

copy-chezmoi-toml host:
    scp ~/.config/chezmoi/chezmoi.toml {{ host }}:~/.config/chezmoi/chezmoi.toml
