name: Auto Merge Dependency Updates
on:
  - pull_request_target
jobs:
  check:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - config: m1
            runner: ubuntu-24.04-arm
          - config: home-server
            runner: ubuntu-24.04
          - config: dell
            runner: ubuntu-24.04
    steps:
      - name: Create nix daemon tmpdir path
        run: |
          sudo mkdir -p /nix/tmpdir
          sudo chown "$(whoami)" /nix/tmpdir

      - name: Install nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GH_PRIVATE_REPO_TOKEN }}
          extra_nix_config: |
            experimental-features = nix-command flakes
            extra-experimental-features = nix-command flakes
            log-lines = 50
            build-dir = /nix/tmpdir

      - uses: cachix/cachix-action@v17
        with:
          name: volodiapg
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Check flat inputs
        run: |
          nix run github:linyinfeng/flat-flake -- check --lock-file ./flake.lock

      - name: Run nix eval for ${{ matrix.config }}
        run: nix eval .#nixosConfigurations.${{ matrix.config }}.config.system.build.toplevel

  auto-merge-dependency-updates:
    needs: check
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: write
      pull-requests: write
    concurrency:
      group: "auto-merge:${{ github.head_ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ secrets.CI_APP_ID }}
          private-key: ${{ secrets.CI_PRIVATE_KEY }}

      - uses: Mic92/auto-merge@main
        with:
          repo-token: ${{ steps.app-token.outputs.token }}
