name: Deploy Config

on:
  push:
    branches:
      - "main"
  check_suite:
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event.check_suite.conclusion == 'success'

    strategy:
      matrix:
        machine:
          - "dell"
          - "home-server"

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Tailscale
      uses: tailscale/github-action@main
      with:
        oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
        oauth-secret: ${{ secrets.TS_OAUTH_CLIENT_SECRET }}
        tags: tag:ci

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@main

    - name: Add agamemnon to known hosts
      id: ssh-known-hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan ${{ matrix.machine }} >> ~/.ssh/known_hosts

    - name: Build and deploy
      run: |
        set -euxo pipefail
        nix flake check
        nix run github:serokell/deploy-rs -- --hostname=${{ matrix.machine }}
