name: Deploy Config

on:
    push:
        branches:
            - "main"
    check_suite:
        types: [completed]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Free Disk Space (Ubuntu)
              uses: jlumbroso/free-disk-space@main
              with:
                  # this might remove tools that are actually needed,
                  # if set to "true" but frees about 6 GB
                  tool-cache: true
                  # all of these default to true, but feel free to set to
                  # "false" if necessary for your workflow
                  android: true
                  dotnet: true
                  haskell: true
                  large-packages: true
                  docker-images: true
                  swap-storage: true

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Tailscale
              uses: tailscale/github-action@v3
              with:
                  authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

            - name: Install Nix
              uses: DeterminateSystems/nix-installer-action@main

            - uses: DeterminateSystems/magic-nix-cache-action@main

            - name: Install SSH key
              uses: shimataro/ssh-key-action@v2
              with:
                  key: ${{ secrets.SSH_KEY }}
                  known_hosts: ${{ secrets.KNOWN_HOSTS }}
                  if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)

            - name: Build and deploy
              run: |
                  set -euxo pipefail
                  ssh-vvv dell ls -lia
                  # nix flake check
                  # nix run github:serokell/deploy-rs -- --targets .#dell
